In [58]:
import tensorflow_hub as hub

In [59]:
import tensorflow_text as text

In [60]:
preprocess_url='https://www.kaggle.com/models/tensorflow/bert/frameworks/TensorFlow2/variations/en-uncased-preprocess/versions/3'
encoder_url='https://www.kaggle.com/models/tensorflow/bert/frameworks/TensorFlow2/variations/bert-en-uncased-l-12-h-128-a-2/versions/2'

In [61]:
bert_preprocess_model=hub.KerasLayer(preprocess_url)

In [62]:
text_test=['nice movie indeed','I love python programming']
text_preprocessed=bert_preprocess_model(text_test)
text_preprocessed.keys()

dict_keys(['input_mask', 'input_type_ids', 'input_word_ids'])

In [63]:
text_preprocessed['input_mask']

<tf.Tensor: shape=(2, 128), dtype=int32, numpy=
array([[1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])>

In [64]:
text_preprocessed['input_type_ids']

<tf.Tensor: shape=(2, 128), dtype=int32, numpy=
array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])>

In [65]:
text_preprocessed['input_word_ids']

<tf.Tensor: shape=(2, 128), dtype=int32, numpy=
array([[  101,  3835,  3185,  5262,   102,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0, 

In [66]:
bert_model=hub.KerasLayer(encoder_url)
bert_results=bert_model(text_preprocessed)
bert_results.keys()

dict_keys(['sequence_output', 'pooled_output', 'encoder_outputs', 'default'])

In [73]:
bert_results['pooled_output']

<tf.Tensor: shape=(2, 128), dtype=float32, numpy=
array([[ 0.9995228 ,  0.92276704, -0.75398797,  0.346511  , -0.98401254,
        -0.7782838 ,  0.1303584 , -0.01245961, -0.7450404 ,  0.9770068 ,
         0.9927735 , -0.70800465,  0.12629116, -0.08128744, -0.91659135,
        -0.70674616,  0.04706702,  0.5003264 , -0.56672764,  0.78900665,
        -0.96310943,  0.99857634,  0.86836576,  0.99796355, -0.6967101 ,
         0.8571637 ,  0.11268854, -0.91914827,  0.8768469 ,  0.93126756,
         0.7966196 ,  0.9932958 ,  0.08000381, -0.01027802,  0.01413055,
         0.7768557 , -0.9609695 , -0.9992023 , -0.9538004 , -0.95843875,
         0.9375277 , -0.8550949 ,  0.93675333,  0.17758591,  0.30764994,
         0.82264906, -0.8868286 , -0.9620807 , -0.63722867,  0.87861097,
         0.8384467 ,  0.35850954,  0.9848917 , -0.6816949 ,  0.05471256,
        -0.7200269 ,  0.86269885, -0.60332465,  0.00379434,  0.9941515 ,
         0.9849127 ,  0.99173963,  0.4255498 , -0.08006652,  0.36191025,
 

In [75]:
bert_results['sequence_output']

<tf.Tensor: shape=(2, 128, 128), dtype=float32, numpy=
array([[[-0.412868  ,  0.9325165 ,  1.2111126 , ..., -0.67740166,
         -0.27916157, -0.2666186 ],
        [ 0.4743836 , -0.88670254,  0.6463562 , ..., -1.4541897 ,
         -0.2131175 ,  0.22514594],
        [ 1.1297076 , -1.0705247 ,  0.71437085, ..., -0.39057407,
         -1.2261691 ,  0.75010866],
        ...,
        [ 0.52308226,  0.24338567, -0.06625827, ..., -0.9355843 ,
         -0.955564  , -0.70738137],
        [-0.613816  ,  0.30972582,  0.30004728, ..., -1.2237943 ,
         -0.7372947 , -0.07605602],
        [-1.258682  ,  0.3297071 ,  0.601883  , ..., -1.4706621 ,
         -0.5748472 ,  0.3141131 ]],

       [[-1.0301841 ,  1.0411872 ,  1.565014  , ..., -0.43635884,
         -0.53341   , -0.5554846 ],
        [-0.14358516, -0.8487002 , -0.13149038, ..., -1.2912191 ,
          0.8955294 , -0.3441497 ],
        [-0.30950496, -0.67586374, -0.13348551, ..., -0.12244528,
          0.75611115, -0.49980927],
        ...,

In [76]:
len(bert_results['encoder_outputs'])

12

In [78]:
bert_results['encoder_outputs'][0]

<tf.Tensor: shape=(2, 128, 128), dtype=float32, numpy=
array([[[-8.9390948e-04,  8.8419892e-02, -3.5727620e-01, ...,
         -2.0122750e-01, -3.8874498e-01,  1.0705048e+00],
        [-3.1803840e-01, -1.1497127e+00, -6.3180521e-02, ...,
         -2.1253562e+00,  5.1944155e-01,  1.6347399e+00],
        [ 1.3655734e+00, -4.6330988e-01,  9.4402528e-01, ...,
         -9.0232074e-01, -1.9444818e+00,  1.7323729e+00],
        ...,
        [-4.4605023e-01,  6.9321953e-02, -1.2824444e+00, ...,
         -6.8856782e-01, -6.1641030e-02,  3.6703596e-01],
        [-3.1645361e-01, -1.8566427e-01, -1.1784329e+00, ...,
         -1.0263462e+00,  2.2365659e-01,  3.6891270e-01],
        [-3.9497891e-01, -3.0476156e-01, -1.0320083e+00, ...,
         -1.0367622e+00,  1.7451988e-01,  4.0061098e-01]],

       [[-8.5741423e-02,  3.9320612e-01, -2.0452949e-01, ...,
         -2.9300258e-01, -5.1257855e-01,  9.5381135e-01],
        [ 2.4231759e-01,  3.2553530e-01, -5.9853321e-01, ...,
         -2.3907437e+00,  2.

In [79]:
bert_results['encoder_outputs'][-1]

<tf.Tensor: shape=(2, 128, 128), dtype=float32, numpy=
array([[[-0.412868  ,  0.9325165 ,  1.2111126 , ..., -0.67740166,
         -0.27916157, -0.2666186 ],
        [ 0.4743836 , -0.88670254,  0.6463562 , ..., -1.4541897 ,
         -0.2131175 ,  0.22514594],
        [ 1.1297076 , -1.0705247 ,  0.71437085, ..., -0.39057407,
         -1.2261691 ,  0.75010866],
        ...,
        [ 0.52308226,  0.24338567, -0.06625827, ..., -0.9355843 ,
         -0.955564  , -0.70738137],
        [-0.613816  ,  0.30972582,  0.30004728, ..., -1.2237943 ,
         -0.7372947 , -0.07605602],
        [-1.258682  ,  0.3297071 ,  0.601883  , ..., -1.4706621 ,
         -0.5748472 ,  0.3141131 ]],

       [[-1.0301841 ,  1.0411872 ,  1.565014  , ..., -0.43635884,
         -0.53341   , -0.5554846 ],
        [-0.14358516, -0.8487002 , -0.13149038, ..., -1.2912191 ,
          0.8955294 , -0.3441497 ],
        [-0.30950496, -0.67586374, -0.13348551, ..., -0.12244528,
          0.75611115, -0.49980927],
        ...,

In [80]:
bert_results['encoder_outputs'][-1]==bert_results['sequence_output']

<tf.Tensor: shape=(2, 128, 128), dtype=bool, numpy=
array([[[ True,  True,  True, ...,  True,  True,  True],
        [ True,  True,  True, ...,  True,  True,  True],
        [ True,  True,  True, ...,  True,  True,  True],
        ...,
        [ True,  True,  True, ...,  True,  True,  True],
        [ True,  True,  True, ...,  True,  True,  True],
        [ True,  True,  True, ...,  True,  True,  True]],

       [[ True,  True,  True, ...,  True,  True,  True],
        [ True,  True,  True, ...,  True,  True,  True],
        [ True,  True,  True, ...,  True,  True,  True],
        ...,
        [ True,  True,  True, ...,  True,  True,  True],
        [ True,  True,  True, ...,  True,  True,  True],
        [ True,  True,  True, ...,  True,  True,  True]]])>