In [1]:
import numpy as np
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.layers import Flatten
from tensorflow.keras.layers import Embedding

In [2]:
reviews=['nice food',
         'amazing restaurant',
         'too good',
         'just loved it',
         'will go again',
         'horrible food',
         'never go there',
         'poor service',
         'poor quality',
         'needs improvement']

sentiment=np.array([1,1,1,1,1,0,0,0,0,0])

In [3]:
one_hot('amazing restaurant',30)

[8, 14]

In [4]:
vocab_size=30
encoded_reviews=[one_hot(d,vocab_size) for d in reviews]
encoded_reviews

[[5, 20],
 [8, 14],
 [22, 6],
 [26, 6, 23],
 [15, 11, 29],
 [23, 20],
 [5, 11, 4],
 [17, 17],
 [17, 11],
 [19, 28]]

In [5]:
max_length=3
padded_reviews=pad_sequences(encoded_reviews,maxlen=max_length,padding='post')
padded_reviews

array([[ 5, 20,  0],
       [ 8, 14,  0],
       [22,  6,  0],
       [26,  6, 23],
       [15, 11, 29],
       [23, 20,  0],
       [ 5, 11,  4],
       [17, 17,  0],
       [17, 11,  0],
       [19, 28,  0]])

In [6]:
embeded_vector_size=4

model=Sequential()
model.add(Embedding(vocab_size,embeded_vector_size,input_length=max_length,name='embedding'))
model.add(Flatten())
model.add(Dense(1,activation='sigmoid'))

In [7]:
X=padded_reviews
y=sentiment

In [8]:
model.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 3, 4)              120       
                                                                 
 flatten (Flatten)           (None, 12)                0         
                                                                 
 dense (Dense)               (None, 1)                 13        
                                                                 
Total params: 133
Trainable params: 133
Non-trainable params: 0
_________________________________________________________________


In [9]:
model.fit(X,y,epochs=50,verbose=0)

In [10]:
loss,accuracy=model.evaluate(X,y)
accuracy

1/1 [==============================] - 0s 211ms/step - loss: 0.6288 - accuracy: 1.0000


1.0

In [11]:
model.get_layer('embedding').get_weights()[0]

array([[ 0.0206407 ,  0.01690362,  0.09696453, -0.07039004],
       [-0.0044992 , -0.03889978,  0.03250741,  0.01702872],
       [ 0.00025439, -0.02010649,  0.01342629, -0.01016892],
       [ 0.03741354, -0.04524485, -0.04042051,  0.01713418],
       [ 0.06696802,  0.03767754,  0.03639576, -0.09739731],
       [ 0.05113935,  0.02239038, -0.00570373,  0.05041476],
       [-0.06336839, -0.06130264,  0.06532104, -0.08252654],
       [ 0.03140396,  0.03048063, -0.03771585,  0.00274171],
       [ 0.02636729,  0.00515879,  0.03048792,  0.09245142],
       [-0.03745623,  0.04318459,  0.00789184, -0.01184858],
       [-0.00714742,  0.01875733,  0.00735059,  0.03770181],
       [ 0.08952121,  0.03495721, -0.08969177,  0.064299  ],
       [ 0.0059749 ,  0.02242449,  0.00516549, -0.04083176],
       [ 0.01570976,  0.04557845, -0.00063521, -0.00836308],
       [-0.05909605, -0.04184291,  0.00521322, -0.0857345 ],
       [ 0.09345327,  0.0297541 ,  0.05309514,  0.07463012],
       [-0.035537  ,  0.

In [12]:
weights=model.get_layer('embedding').get_weights()[0]
len(weights)

30

In [17]:
weights[5]

array([ 0.05113935,  0.02239038, -0.00570373,  0.05041476], dtype=float32)

In [18]:
weights[8]

array([0.02636729, 0.00515879, 0.03048792, 0.09245142], dtype=float32)