In [34]:
from transformers import pipeline
from transformers import AutoTokenizer, AutoModel, TFAutoModel, AutoModelForSequenceClassification
import torch
import torch.nn.functional as F

In [2]:
classifier = pipeline('sentiment-analysis')

No model was supplied, defaulted to distilbert/distilbert-base-uncased-finetuned-sst-2-english and revision 714eb0f (https://huggingface.co/distilbert/distilbert-base-uncased-finetuned-sst-2-english).
Using a pipeline without specifying a model name and revision in production is not recommended.


config.json:   0%|          | 0.00/629 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/268M [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/48.0 [00:00<?, ?B/s]

vocab.txt: 0.00B [00:00, ?B/s]

Device set to use cuda:0


In [3]:
classifier('we are happy to buy a new book.')

[{'label': 'POSITIVE', 'score': 0.9998507499694824}]

In [5]:
tokenizer = AutoTokenizer.from_pretrained('bert-base-uncased')

tokenizer_config.json:   0%|          | 0.00/48.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/570 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/466k [00:00<?, ?B/s]

In [6]:
model = AutoModel.from_pretrained('bert-base-uncased')

model.safetensors:   0%|          | 0.00/440M [00:00<?, ?B/s]

In [7]:
txt = 'Hello World'

In [8]:
inp = tokenizer(txt, return_tensors = 'pt')

In [10]:
out = model(**inp)

In [11]:
out

BaseModelOutputWithPoolingAndCrossAttentions(last_hidden_state=tensor([[[-0.1689,  0.1361, -0.1394,  ..., -0.6251,  0.0522,  0.3671],
         [-0.3633,  0.1412,  0.8800,  ...,  0.1043,  0.2888,  0.3727],
         [-0.6986, -0.6988,  0.0645,  ..., -0.2210,  0.0099, -0.5940],
         [ 0.8310,  0.1237, -0.1512,  ...,  0.1031, -0.6779, -0.2629]]],
       grad_fn=<NativeLayerNormBackward0>), pooler_output=tensor([[-9.0615e-01, -3.1115e-01, -6.2165e-01,  7.7409e-01,  2.8987e-01,
         -1.9024e-01,  9.2471e-01,  1.8180e-01, -5.0504e-01, -9.9994e-01,
         -2.3735e-01,  8.7621e-01,  9.7716e-01,  2.5809e-01,  9.3801e-01,
         -6.9061e-01, -5.2105e-01, -5.4915e-01,  3.5759e-01, -7.5982e-01,
          6.0571e-01,  9.9936e-01,  3.3454e-01,  2.5202e-01,  4.1586e-01,
          9.7050e-01, -7.8426e-01,  9.3400e-01,  9.6314e-01,  6.5928e-01,
         -7.1543e-01,  1.0239e-01, -9.8550e-01, -1.6261e-01, -6.7724e-01,
         -9.8579e-01,  3.0743e-01, -7.8618e-01,  1.3032e-01,  1.2667e-02,
 

In [13]:
tfmodel = TFAutoModel.from_pretrained('bert-base-uncased')

I0000 00:00:1751100149.007853      35 gpu_device.cc:2022] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 13624 MB memory:  -> device: 0, name: Tesla T4, pci bus id: 0000:00:04.0, compute capability: 7.5
I0000 00:00:1751100149.008628      35 gpu_device.cc:2022] Created device /job:localhost/replica:0/task:0/device:GPU:1 with 13942 MB memory:  -> device: 1, name: Tesla T4, pci bus id: 0000:00:05.0, compute capability: 7.5
Some weights of the PyTorch model were not used when initializing the TF 2.0 model TFBertModel: ['cls.predictions.transform.LayerNorm.bias', 'cls.predictions.bias', 'cls.seq_relationship.bias', 'cls.predictions.transform.dense.weight', 'cls.predictions.transform.dense.bias', 'cls.seq_relationship.weight', 'cls.predictions.transform.LayerNorm.weight']
- This IS expected if you are initializing TFBertModel from a PyTorch model trained on another task or with another architecture (e.g. initializing a TFBertForSequenceClassification model from a BertForPre

In [17]:
tfinp = tokenizer(txt, return_tensors = 'tf')

In [18]:
tfout = tfmodel(**tfinp)

In [19]:
tfout

TFBaseModelOutputWithPoolingAndCrossAttentions(last_hidden_state=<tf.Tensor: shape=(1, 4, 768), dtype=float32, numpy=
array([[[-0.16888325,  0.13606334, -0.13940078, ..., -0.62511253,
          0.05217267,  0.3671455 ],
        [-0.3632744 ,  0.14121872,  0.879987  , ...,  0.10432988,
          0.28875676,  0.37267905],
        [-0.69859445, -0.6987977 ,  0.06450161, ..., -0.22103643,
          0.00986908, -0.5939799 ],
        [ 0.83098286,  0.12366741, -0.15119024, ...,  0.10309598,
         -0.67792666, -0.26285192]]], dtype=float32)>, pooler_output=<tf.Tensor: shape=(1, 768), dtype=float32, numpy=
array([[-9.06153381e-01, -3.11153024e-01, -6.21653378e-01,
         7.74093091e-01,  2.89865613e-01, -1.90243453e-01,
         9.24707890e-01,  1.81800961e-01, -5.05039275e-01,
        -9.99944508e-01, -2.37347841e-01,  8.76212180e-01,
         9.77160513e-01,  2.58089840e-01,  9.38015044e-01,
        -6.90611601e-01, -5.21052063e-01, -5.49152911e-01,
         3.57588738e-01, -7.59822488e

In [21]:
model_name = 'distilbert-base-uncased-finetuned-sst-2-english'

In [22]:
model = AutoModelForSequenceClassification.from_pretrained(model_name)

config.json:   0%|          | 0.00/629 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/268M [00:00<?, ?B/s]

In [23]:
tokenizer = AutoTokenizer.from_pretrained(model_name)

tokenizer_config.json:   0%|          | 0.00/48.0 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

In [24]:
classifier = pipeline('sentiment-analysis', model = model, tokenizer = tokenizer)

Device set to use cuda:0


In [25]:
results = classifier(["We are very happy to show you the Transformers library.", "We hope you don't hate it."])
for result in results:
    print(result)

{'label': 'POSITIVE', 'score': 0.9997994303703308}
{'label': 'NEGATIVE', 'score': 0.5308588147163391}


In [26]:
tokens = tokenizer.tokenize("We are very happy to show you the Transformers library.")

In [28]:
tokens

['we',
 'are',
 'very',
 'happy',
 'to',
 'show',
 'you',
 'the',
 'transformers',
 'library',
 '.']

In [29]:
token_ids = tokenizer.convert_tokens_to_ids(tokens)

In [30]:
token_ids

[2057, 2024, 2200, 3407, 2000, 2265, 2017, 1996, 19081, 3075, 1012]

In [31]:
input_ids = tokenizer("We are very happy to show you the Transformers library.")

In [32]:
input_ids

{'input_ids': [101, 2057, 2024, 2200, 3407, 2000, 2265, 2017, 1996, 19081, 3075, 1012, 102], 'attention_mask': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]}

In [33]:
X_train = ["We are very happy to show you the Transformers library.",
          "We hope you don't hate it."]
batch = tokenizer(X_train, padding = True, truncation = True, max_length = 512, return_tensors = 'pt')
print(batch)

{'input_ids': tensor([[  101,  2057,  2024,  2200,  3407,  2000,  2265,  2017,  1996, 19081,
          3075,  1012,   102],
        [  101,  2057,  3246,  2017,  2123,  1005,  1056,  5223,  2009,  1012,
           102,     0,     0]]), 'attention_mask': tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0]])}


In [38]:
device = 'cuda'

In [40]:
model = model.to(device)
batch = batch.to(device)
with torch.no_grad():
    outputs = model(**batch)
    predictions = F.softmax(outputs.logits, dim=1)
    labels = torch.argmax(predictions, dim=1)
    print(labels)
    labels = [model.config.id2label[label_id] for label_id in labels.tolist()]
    print(labels)

tensor([1, 0], device='cuda:0')
['POSITIVE', 'NEGATIVE']
